test cases added for address book, category, customer service layer
mariappan-sivakumar-zuci/E-Commerce pull request #47
Opened 2023-11-08 13:58 UTC by mariappan-sivakumar-zuci

Hi Jithu,
I have added testcases for 3service layer we met with a error on Monday the whole day is spend on that error after that. We are surf on the internet to study how to write unit test cases. so why two days we didn't make any pull request
If you found any correction please let me know.

2023-11-09 07:27 UTC, mariappan-sivakumar-zuci commented
Hi Jithu,
I have added category and subcategory test In this commit I starting working on writing testcase for Product service layer but I didn't complete that.

2023-11-09 09:56 UTC, jithuzuci commented on src/main/java/com/app/shopping/ecommerce/entity/Order.java
> +//    private List<Product> products;
Why is it commented on here? If not needed can you please remove it?

2023-11-09 10:18 UTC, jithuzuci requested changes
I have made a change request, please address it before merging.

2023-11-09 10:21 UTC, jithuzuci commented
Also, as mentioned in the previous PR comment  https://github.com/mariappan-sivakumar-zuci/E-Commerce/pull/46#pullrequestreview-1712724428, Please try to make smaller PR's otherwise it's hard to review. You can try something like a PR per service or methods.
Also, you can split the work within your group and raise separate PRs?

2023-11-09 14:01 UTC, Jaya-Anand-Natesan commented on src/main/java/com/app/shopping/ecommerce/services/SupplierService.java
> +    SupplierReg registrationSupplier(SupplierReg supplierreg);
Okay Sure 
I will change it.
Thank you.

2023-11-10 04:18 UTC, mariappan-sivakumar-zuci commented on src/main/java/com/app/shopping/ecommerce/entity/Order.java
> +//    private List<Product> products;
We are hold the process in order entity. with the list of product we face difficulties in the database section with out the annotations that's why we commented it after some time we will un-commend it and work on it

2023-11-17 06:17 UTC, jithuzuci approved these changes
Thanks for making the changes. It looks good to me.

2023-11-17 09:46 UTC, merged

2023-11-17 09:47 UTC, mariappan-sivakumar-zuci commented
Ok Jithu

2023-11-24 08:49 UTC, Jaya-Anand-Natesan commented
Thank you Jithu. It means a lot..