testcases for FullwidthDisplayFeaturedPromosService service layer
mariappan-sivakumar-zuci/E-Commerce pull request #48
Opened 2023-11-09 14:04 UTC by Rajkumar-Selvaraj

I have added testcases for "FullwidthDisplayFeaturedPromosService" service layer.

2023-11-17 06:15 UTC, jithuzuci requested changes

2023-11-17 06:15 UTC, jithuzuci commented on src/main/java/com/app/shopping/ecommerce/entity/Order.java
> -package com.app.shopping.ecommerce.entity;
Why is this entire file commented on?

2023-11-17 06:15 UTC, jithuzuci commented on src/main/java/com/app/shopping/ecommerce/repository/UserRepository.java
> +@Repository
Just for curiosity. Why can't we use `@JpaRepository` instead?

2023-12-12 05:19 UTC, Rajkumar-Selvaraj commented on src/main/java/com/app/shopping/ecommerce/entity/Order.java
> -package com.app.shopping.ecommerce.entity;
Due to error, I commented this class fully. I resolved the error. But I forgot to uncomment it.

2023-12-12 05:46 UTC, Rajkumar-Selvaraj commented on src/main/java/com/app/shopping/ecommerce/repository/UserRepository.java
> +@Repository
Actually, We don't need to use @Repository annotations when we extends our interface with JPArepository interface. The Springboot automatically identify it as an Repository bean. The reason why I used the @Repository annotation here, because I always used to annotate just for the clarity.

2023-12-12 12:48 UTC, jithuzuci approved these changes
Overall changes look good to me.

2023-12-12 17:58 UTC, merged